---
authors:
  - Ansible Network Community (ansible-network)
license_file: LICENSE
name: ansible
description: Ansible Network Collection for Arista EOS devices.
namespace: network
readme: README.md
repository: https://github.com/ansible-collections/ansible.network
tags: [networking, security, cloud, network_cli, netconf, httpapi, grpc]
# NOTE(pabelanger): We create an empty version key to keep ansible-galaxy
# happy. We dynamically inject version info based on git information.
version: null
