- hosts: ios
  gather_facts: no
  tasks:
  - name: invoke gather fuctnion
    include_role:
      name: resource_manager
      tasks_from: gather
    vars:
      ansible_network_os: cisco.ios.ios
      resources:
        - 'interfaces'
        - 'l2_interfaces'
        - 'l3_interfaces'
