---
- hosts: ios
  gather_facts: false
  tasks:
  - name: invoke gather fuctnion
    include_role:
      name: resource_manager
    vars:
      perform_task: gather
      ansible_network_os: cisco.ios.ios
      resources:
        - 'interfaces'
        - 'l2_interfaces'
        - 'l3_interfaces'
