---
- name: Gather the supported resource modules
  ansible.netcommon.network_resource:
    os_name: "{{ ansible_network_os }}"
  register: network_resources_list

- set_fact:
    resources: "{{ network_resources_list['modules'] }}"
  when: resources is undefined

- set_fact:
    network_resources: "{{ network_resources_list['modules']|ansible.utils.resource_list_compare(resources) }}"

- include_tasks: includes/build.yml
  loop: "{{ network_resources['actionable'] }}"
