---
- name: Run the platform facts module
  action:
    module: "ansible.netcommon.resource_module"
    os_name: "{{ ansible_network_os }}"
  register: network_resources_list

- set_fact:
    network_resources: "{{ network_resources_list['modules']|param_list_compare(resources) }}"

- include_tasks: includes/build.yml
  loop: "{{ network_resources['actionable'] }}"

- name: Run the platform facts module
  action:
    module: "ansible.netcommon.resource_module"
    os_name: "{{ ansible_network_os }}"
    name: "{{ item }}"
    state: gathered
  loop: "{{ network_resources['actionable'] }}"


