---
- name: Create inventory directory
  file:
    path: "{{ inventory_directory }}/host_vars/{{ ansible_network_os }}/{{ inventory_hostname }}"
    state: directory

- name: Write each resource to a file
  copy:
    content: "{{ {item: result['gathered']} | to_nice_yaml }}"
    dest: "{{ inventory_directory }}/host_vars/{{ ansible_network_os }}/{{ inventory_hostname }}/{{ item }}.yaml"
